### PR TITLE
remove Cargo.lock and add Cargo.lock in .gitignore

### PR DESCRIPTION
**Pull request by orzogc**
Don't need the Cargo.lock in a lib.
see https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

### CODE REVIEW

**Comment by SfietKonstantin** [comment]
Thanks for the heads-up !

**Comment by SfietKonstantin** [comment]
OK. It breaks the MRV of 1.44 (because of dependencies), so I will have to have a look at it ...

**Comment by orzogc** [comment]
MSRV should be fixed now.

**Comment by SfietKonstantin** [comment]
Let's run the CI and we will see :)

**Comment by SfietKonstantin** [comment]
Thanks a lot for this PR @orzogc !

**Pull request merged**
